/**
 * Sky Ariana Logistics — Operations Report Multi-Sheet Excel & UTF-8 CSV Export Engine
 * 
 * Generates management-ready Excel (.xlsx) workbooks and UTF-8 CSV files with BOM
 * preserving Pashto/Dari text, Afghan truck plates, and multi-currency segregation.
 */

import * as XLSX from "xlsx"
import { OperationsReportModel } from "./types"

/**
 * Sanitizes file names to be Windows, macOS, and Linux safe.
 * Replaces illegal Windows characters (/ \ : * ? " < > |) with hyphens.
 */
export function getWindowsSafeReportFileName(title: string, extension: string = "xlsx"): string {
  const sanitizedTitle = title
    .replace(/[\\/:*?"<>|]+/g, "-")
    .replace(/\s+/g, "_")
    .replace(/[-_]+/g, "-")
    .replace(/^[-_.]+|[-_.]+$/g, "")

  const cleanExt = extension.replace(/^\./, "")
  return `${sanitizedTitle || "Sky_Ariana_Operations_Report"}.${cleanExt}`
}

/**
 * Helper to compute auto column widths for Excel sheets
 */
function autoFitColumns(rows: (string | number | undefined | null)[][]): { wch: number }[] {
  const colWidths: number[] = []

  for (const row of rows) {
    row.forEach((val, colIdx) => {
      const len = val !== null && val !== undefined ? String(val).length : 0
      colWidths[colIdx] = Math.max(colWidths[colIdx] || 10, len + 3)
    })
  }

  return colWidths.map((w) => ({ wch: Math.min(Math.max(w, 12), 50) }))
}

/**
 * Trigger client-side file download for Blob data
 */
function triggerDownload(blob: Blob, filename: string): void {
  if (typeof window === "undefined") return

  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

/**
 * Exports the Operations Report Model to a structured multi-sheet Excel (.xlsx) workbook.
 */
export function exportOperationsReportToExcel(
  report: OperationsReportModel,
  customFileName?: string
): void {
  const wb = XLSX.utils.book_new()
  const { metadata, summary, shipments, routeActivity, containerActivity, truckActivity, borderActivity, portActivity, documentStatusSummary, needsAttention, topShippers, topConsignees, topCommodities } = report

  // =========================================================================
  // SHEET 1: EXECUTIVE SUMMARY
  // =========================================================================
  const summaryRows: (string | number)[][] = [
    ["SKY ARIANA LIMITED — OPERATIONS MANAGEMENT REPORT"],
    [`Report Title: ${metadata.title}`],
    [`Period Type: ${metadata.periodType.toUpperCase()}`, `Date Range: ${metadata.dateRangeLabel}`],
    [`Generated At: ${metadata.generatedAt}`, `Generated By: ${metadata.generatedBy}`],
    [`Filter Origin: ${metadata.appliedFilters.origin || "All"}`, `Filter Destination: ${metadata.appliedFilters.destination || "All"}`],
    [],
    ["========================================================================="],
    ["KEY PERFORMANCE INDICATORS (KPI)", "VALUE", "UNIT"],
    ["========================================================================="],
    ["Total Shipments", summary.totalShipments, "Shipments"],
    ["Active Shipments", summary.activeShipments, "Shipments"],
    ["Delivered Shipments", summary.deliveredShipments, "Shipments"],
    ["Total Containers", summary.totalContainers, "Containers"],
    ["Total Trucks Dispatched", summary.totalTrucks, "Trucks"],
    ["Total Cargo Packages", summary.totalPackages, "Cartons/Packages"],
    ["Total Gross Weight (KG)", summary.totalGrossWeightKg.toLocaleString(), "KG"],
    ["Total Gross Weight (MT)", (summary.totalGrossWeightKg / 1000).toFixed(2), "Metric Tons"],
    ["Total Net Weight (KG)", summary.totalNetWeightKg.toLocaleString(), "KG"],
    ["Total Net Weight (MT)", (summary.totalNetWeightKg / 1000).toFixed(2), "Metric Tons"],
    ["Needs Attention Issues", summary.needsAttentionCount, "Shipments / Items"],
    [],
    ["========================================================================="],
    ["OPERATIONAL STATUS BREAKDOWN", "COUNT", "% OF ACTIVE"],
    ["========================================================================="],
  ]

  for (const cat of summary.statusCategories) {
    summaryRows.push([cat.statusCategory, cat.count, `${cat.percentage.toFixed(1)}%`])
  }

  summaryRows.push([])
  summaryRows.push(["========================================================================="])
  summaryRows.push(["FINANCIAL TOTALS (SEGREGATED BY CURRENCY - NO MIXING)", "AMOUNT", "CURRENCY"])
  summaryRows.push(["========================================================================="])

  for (const [curr, amt] of Object.entries(summary.totalRevenueByCurrency)) {
    summaryRows.push(["Total Revenue / Value", amt.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 }), curr])
  }
  for (const [curr, amt] of Object.entries(summary.totalDriverRentByCurrency)) {
    summaryRows.push(["Total Driver Rent (Dispatched)", amt.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 }), curr])
  }

  if (metadata.notes) {
    summaryRows.push([])
    summaryRows.push(["MANAGEMENT OPERATIONS NOTES:"])
    summaryRows.push([metadata.notes])
  }

  const wsSummary = XLSX.utils.aoa_to_sheet(summaryRows)
  wsSummary["!cols"] = autoFitColumns(summaryRows)
  XLSX.utils.book_append_sheet(wb, wsSummary, "Executive Summary")

  // =========================================================================
  // SHEET 2: SHIPMENT ACTIVITY
  // =========================================================================
  const shipmentRows: (string | number)[][] = [
    [
      "BOL Number",
      "Tracking Number",
      "Issue Date",
      "Shipper Name",
      "Consignee Name",
      "Commodity",
      "Packages",
      "Gross Weight (KG)",
      "Net Weight (KG)",
      "Origin",
      "Destination",
      "Border Crossing",
      "Port of Entry/Exit",
      "Driver Name",
      "Afghan Truck Plate",
      "Driver Rent",
      "Rent Currency",
      "Operational Status",
      "Needs Attention",
    ],
  ]

  for (const item of shipments) {
    shipmentRows.push([
      item.bolNumber,
      item.trackingNumber,
      item.issueDate,
      item.shipperName,
      item.consigneeName,
      item.commodity,
      item.packages,
      item.grossWeightKg,
      item.netWeightKg,
      item.origin,
      item.destination,
      item.borderCrossing,
      item.port,
      item.driverName,
      item.truckNumber, // Afghan plate preserved as string
      item.driverRent,
      item.rentCurrency,
      item.operationalStatus,
      item.needsAttention ? item.attentionReasons.join("; ") : "No",
    ])
  }

  const wsShipments = XLSX.utils.aoa_to_sheet(shipmentRows)
  wsShipments["!cols"] = autoFitColumns(shipmentRows)
  XLSX.utils.book_append_sheet(wb, wsShipments, "Shipment Activity")

  // =========================================================================
  // SHEET 3: CONTAINER MOVEMENTS
  // =========================================================================
  const containerRows: (string | number)[][] = [
    [
      "Container Number",
      "Size / Type",
      "Category",
      "BOL Number",
      "Shipper",
      "Consignee",
      "Origin",
      "Destination",
      "Port",
      "Operational Status",
    ],
  ]

  for (const c of containerActivity) {
    containerRows.push([
      c.containerNumber,
      c.containerType,
      c.category,
      c.bolNumber,
      c.shipper,
      c.consignee,
      c.origin,
      c.destination,
      c.port,
      c.status,
    ])
  }

  const wsContainers = XLSX.utils.aoa_to_sheet(containerRows)
  wsContainers["!cols"] = autoFitColumns(containerRows)
  XLSX.utils.book_append_sheet(wb, wsContainers, "Container Movements")

  // =========================================================================
  // SHEET 4: TRUCK & BORDER ACTIVITY
  // =========================================================================
  const truckRows: (string | number)[][] = [
    [
      "Afghan Truck Plate",
      "Driver Name",
      "Father Name",
      "Phone Number",
      "Origin",
      "Border Crossing",
      "Port / Destination",
      "BOL Number",
      "Rent Amount",
      "Rent Currency",
      "Status",
    ],
  ]

  for (const t of truckActivity) {
    truckRows.push([
      t.truckNumber, // Afghan plate preserved as string
      t.driverName,
      t.driverFatherName,
      t.driverPhone,
      t.origin,
      t.borderCrossing,
      t.destination,
      t.bolNumber,
      t.rentAmount,
      t.rentCurrency,
      t.status,
    ])
  }

  const wsTrucks = XLSX.utils.aoa_to_sheet(truckRows)
  wsTrucks["!cols"] = autoFitColumns(truckRows)
  XLSX.utils.book_append_sheet(wb, wsTrucks, "Truck & Border Activity")

  // =========================================================================
  // SHEET 5: ROUTE & PORT ACTIVITY
  // =========================================================================
  const routeRows: (string | number)[][] = [
    [
      "Route Description",
      "Origin",
      "Transit Border",
      "Port",
      "Destination",
      "Shipments Count",
      "Containers Count",
      "Gross Weight (KG)",
      "Gross Weight (MT)",
    ],
  ]

  for (const r of routeActivity) {
    routeRows.push([
      r.route,
      r.origin,
      r.border,
      r.port,
      r.destination,
      r.shipmentCount,
      r.containerCount,
      r.grossWeightKg,
      (r.grossWeightKg / 1000).toFixed(2),
    ])
  }

  const wsRoutes = XLSX.utils.aoa_to_sheet(routeRows)
  wsRoutes["!cols"] = autoFitColumns(routeRows)
  XLSX.utils.book_append_sheet(wb, wsRoutes, "Routes & Gateways")

  // =========================================================================
  // SHEET 6: DOCUMENT CHECKLIST
  // =========================================================================
  const docRows: (string | number)[][] = [
    [
      "BOL Number",
      "Shipper Name",
      "Consignee Name",
      "BOL Document",
      "Commercial Invoice",
      "Packing List",
      "Transit Paper",
      "Phytosanitary Certificate",
      "Missing Document Count",
      "Document Status",
    ],
  ]

  for (const d of documentStatusSummary) {
    docRows.push([
      d.bolNumber,
      d.shipperName,
      d.consigneeName,
      d.hasBol ? "Complete" : "Pending",
      d.hasCommercialInvoice ? "Complete" : "Pending",
      d.hasPackingList ? "Complete" : "Pending",
      d.hasTransitPaper ? "Complete" : "Pending",
      d.hasPhyto ? "Complete" : "Pending",
      d.missingCount,
      d.isComplete ? "All Complete" : `${d.missingCount} Missing`,
    ])
  }

  const wsDocs = XLSX.utils.aoa_to_sheet(docRows)
  wsDocs["!cols"] = autoFitColumns(docRows)
  XLSX.utils.book_append_sheet(wb, wsDocs, "Document Checklist")

  // =========================================================================
  // SHEET 7: NEEDS ATTENTION
  // =========================================================================
  const attentionRows: (string | number)[][] = [
    ["Severity", "BOL Number", "Issue Title", "Issue Description", "Action Required"],
  ]

  for (const item of needsAttention) {
    attentionRows.push([
      item.severity.toUpperCase(),
      item.bolNumber,
      item.issue,
      item.description,
      item.suggestedAction,
    ])
  }

  const wsAttention = XLSX.utils.aoa_to_sheet(attentionRows)
  wsAttention["!cols"] = autoFitColumns(attentionRows)
  XLSX.utils.book_append_sheet(wb, wsAttention, "Needs Attention")

  // =========================================================================
  // SHEET 8: TOP STAKEHOLDERS
  // =========================================================================
  const stakeholderRows: (string | number)[][] = [
    ["TOP SHIPPERS", "", "", "", "TOP CONSIGNEES", "", "", "", "TOP COMMODITIES", "", "", ""],
    [
      "Shipper", "Shipments", "Containers", "Weight (KG)",
      "Consignee", "Shipments", "Containers", "Weight (KG)",
      "Commodity", "Shipments", "Containers", "Weight (KG)",
    ],
  ]

  const maxLen = Math.max(topShippers.length, topConsignees.length, topCommodities.length)
  for (let i = 0; i < maxLen; i++) {
    const s = topShippers[i]
    const c = topConsignees[i]
    const m = topCommodities[i]

    stakeholderRows.push([
      s ? s.name : "",
      s ? s.shipmentCount : "",
      s ? s.containerCount : "",
      s ? s.grossWeightKg : "",

      c ? c.name : "",
      c ? c.shipmentCount : "",
      c ? c.containerCount : "",
      c ? c.grossWeightKg : "",

      m ? m.name : "",
      m ? m.shipmentCount : "",
      m ? m.containerCount : "",
      m ? m.grossWeightKg : "",
    ])
  }

  const wsStakeholders = XLSX.utils.aoa_to_sheet(stakeholderRows)
  wsStakeholders["!cols"] = autoFitColumns(stakeholderRows)
  XLSX.utils.book_append_sheet(wb, wsStakeholders, "Top Stakeholders")

  // Generate binary file and trigger download
  const safeFileName = customFileName || getWindowsSafeReportFileName(
    `Sky-Ariana-${report.metadata.title}-${report.metadata.period.startDate}-to-${report.metadata.period.endDate}`,
    "xlsx"
  )

  if (typeof window !== "undefined") {
    const wbout = XLSX.write(wb, { bookType: "xlsx", type: "array" })
    const blob = new Blob([wbout], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" })
    triggerDownload(blob, safeFileName)
  } else {
    XLSX.writeFile(wb, safeFileName)
  }
}

/**
 * Exports the Operations Report to a UTF-8 CSV with BOM (\uFEFF) for Pashto/Dari text preservation.
 */
export function exportOperationsReportToCsv(
  report: OperationsReportModel,
  customFileName?: string
): void {
  const lines: string[] = []

  // UTF-8 BOM is added during Blob creation
  const escapeCsv = (val: string | number | undefined | null): string => {
    if (val === undefined || val === null) return '""'
    const str = String(val)
    if (str.includes('"') || str.includes(",") || str.includes("\n") || str.includes("\r")) {
      return `"${str.replace(/"/g, '""')}"`
    }
    return `"${str}"`
  }

  // Metadata
  lines.push(`${escapeCsv("SKY ARIANA LIMITED — OPERATIONS MANAGEMENT REPORT")}`)
  lines.push(`${escapeCsv("Report Title")},${escapeCsv(report.metadata.title)}`)
  lines.push(`${escapeCsv("Period")},${escapeCsv(report.metadata.dateRangeLabel)}`)
  lines.push(`${escapeCsv("Generated At")},${escapeCsv(report.metadata.generatedAt)}`)
  lines.push(`${escapeCsv("Total Shipments")},${escapeCsv(report.summary.totalShipments)}`)
  lines.push(`${escapeCsv("Total Containers")},${escapeCsv(report.summary.totalContainers)}`)
  lines.push(`${escapeCsv("Total Gross Weight (KG)")},${escapeCsv(report.summary.totalGrossWeightKg)}`)
  lines.push("")

  // Shipments Header
  const headers = [
    "BOL Number",
    "Tracking Number",
    "Issue Date",
    "Shipper Name",
    "Consignee Name",
    "Commodity",
    "Packages",
    "Gross Weight (KG)",
    "Net Weight (KG)",
    "Origin",
    "Destination",
    "Border Crossing",
    "Port",
    "Driver Name",
    "Afghan Truck Plate",
    "Driver Rent",
    "Rent Currency",
    "Operational Status",
    "Needs Attention",
    "Attention Notes",
  ]
  lines.push(headers.map(escapeCsv).join(","))

  // Shipment Data Rows
  for (const s of report.shipments) {
    lines.push([
      escapeCsv(s.bolNumber),
      escapeCsv(s.trackingNumber),
      escapeCsv(s.issueDate),
      escapeCsv(s.shipperName),
      escapeCsv(s.consigneeName),
      escapeCsv(s.commodity),
      escapeCsv(s.packages),
      escapeCsv(s.grossWeightKg),
      escapeCsv(s.netWeightKg),
      escapeCsv(s.origin),
      escapeCsv(s.destination),
      escapeCsv(s.borderCrossing),
      escapeCsv(s.port),
      escapeCsv(s.driverName),
      escapeCsv(s.truckNumber), // Afghan plate preserved as string
      escapeCsv(s.driverRent),
      escapeCsv(s.rentCurrency),
      escapeCsv(s.operationalStatus),
      escapeCsv(s.needsAttention ? "YES" : "NO"),
      escapeCsv(s.attentionReasons.join("; ")),
    ].join(","))
  }

  const csvContent = "\uFEFF" + lines.join("\r\n")
  const safeFileName = customFileName || getWindowsSafeReportFileName(
    `Sky-Ariana-${report.metadata.title}-${report.metadata.period.startDate}-to-${report.metadata.period.endDate}`,
    "csv"
  )

  if (typeof window !== "undefined") {
    const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" })
    triggerDownload(blob, safeFileName)
  }
}
