"""initial_models

Revision ID: 9c12685e0336
Revises: 
Create Date: 2026-09-23 11:20:33.174270
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c12685e0336'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('agent_type', sa.String(length=64), nullable=False),
    sa.Column('border_station', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_agent_type'), ['agent_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_border_station'), ['border_station'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_name'), ['name'], unique=False)

    op.create_table('attachments',
    sa.Column('linked_type', sa.String(length=64), nullable=False),
    sa.Column('linked_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index('ix_attachment_link', ['linked_type', 'linked_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_linked_id'), ['linked_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_linked_type'), ['linked_type'], unique=False)

    op.create_table('audit_logs',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('old_values_json', sa.Text(), nullable=True),
    sa.Column('new_values_json', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index('ix_audit_logs_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('backups',
    sa.Column('backup_filename', sa.String(length=255), nullable=False),
    sa.Column('backup_type', sa.String(length=64), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backups_backup_filename'), ['backup_filename'], unique=True)
        batch_op.create_index(batch_op.f('ix_backups_status'), ['status'], unique=False)

    op.create_table('clients',
    sa.Column('client_name', sa.String(length=160), nullable=False),
    sa.Column('account_number', sa.String(length=64), nullable=True),
    sa.Column('portal_access', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_account_number'), ['account_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_clients_client_name'), ['client_name'], unique=False)

    op.create_table('commodities',
    sa.Column('hs_code', sa.String(length=32), nullable=True),
    sa.Column('commodity_name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_hazardous', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commodities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commodities_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_commodities_commodity_name'), ['commodity_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_commodities_hs_code'), ['hs_code'], unique=False)

    op.create_table('companies',
    sa.Column('company_name', sa.String(length=160), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('tax_number', sa.String(length=64), nullable=True),
    sa.Column('contact_phone', sa.String(length=64), nullable=True),
    sa.Column('contact_email', sa.String(length=160), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_companies_company_name'), ['company_name'], unique=True)

    op.create_table('customers',
    sa.Column('customer_name', sa.String(length=160), nullable=False),
    sa.Column('customer_type', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('company', sa.String(length=160), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_customer_name'), ['customer_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_customer_type'), ['customer_type'], unique=False)

    op.create_table('drivers',
    sa.Column('driver_name', sa.String(length=128), nullable=False),
    sa.Column('father_name', sa.String(length=128), nullable=True),
    sa.Column('national_id', sa.String(length=64), nullable=True),
    sa.Column('passport_number', sa.String(length=64), nullable=True),
    sa.Column('license_number', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drivers_driver_name'), ['driver_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_drivers_license_number'), ['license_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_drivers_national_id'), ['national_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drivers_passport_number'), ['passport_number'], unique=False)

    op.create_table('ledgers',
    sa.Column('account_code', sa.String(length=64), nullable=False),
    sa.Column('account_name', sa.String(length=160), nullable=False),
    sa.Column('account_type', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ledgers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledgers_account_code'), ['account_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_ledgers_account_name'), ['account_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledgers_account_type'), ['account_type'], unique=False)

    op.create_table('locations',
    sa.Column('location_code', sa.String(length=32), nullable=False),
    sa.Column('location_name', sa.String(length=128), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('is_border', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locations_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_locations_location_code'), ['location_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_locations_location_name'), ['location_name'], unique=False)

    op.create_table('notify_parties',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=160), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notify_parties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notify_parties_name'), ['name'], unique=False)

    op.create_table('ports',
    sa.Column('port_code', sa.String(length=32), nullable=False),
    sa.Column('port_name', sa.String(length=128), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('port_type', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ports_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_ports_port_code'), ['port_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_ports_port_name'), ['port_name'], unique=False)

    op.create_table('reports',
    sa.Column('report_name', sa.String(length=160), nullable=False),
    sa.Column('report_type', sa.String(length=64), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('parameters_json', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('format', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_report_name'), ['report_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_report_type'), ['report_type'], unique=False)

    op.create_table('routes',
    sa.Column('route_name', sa.String(length=160), nullable=False),
    sa.Column('origin', sa.String(length=128), nullable=False),
    sa.Column('destination', sa.String(length=128), nullable=False),
    sa.Column('border_crossing', sa.String(length=128), nullable=True),
    sa.Column('distance_km', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('transit_days_estimate', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routes_border_crossing'), ['border_crossing'], unique=False)
        batch_op.create_index(batch_op.f('ix_routes_route_name'), ['route_name'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settings_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_settings_key'), ['key'], unique=True)

    op.create_table('suppliers',
    sa.Column('supplier_name', sa.String(length=160), nullable=False),
    sa.Column('supplier_type', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_supplier_name'), ['supplier_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_supplier_type'), ['supplier_type'], unique=False)

    op.create_table('users',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('consignees',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('contact_person', sa.String(length=160), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consignees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consignees_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_consignees_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consignees_name'), ['name'], unique=False)

    op.create_table('shippers',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('contact_person', sa.String(length=160), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shippers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shippers_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_shippers_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shippers_name'), ['name'], unique=False)

    op.create_table('trucks',
    sa.Column('truck_number', sa.String(length=64), nullable=False),
    sa.Column('driver_id', sa.String(length=36), nullable=True),
    sa.Column('driver_name', sa.String(length=128), nullable=True),
    sa.Column('container_number', sa.String(length=64), nullable=True),
    sa.Column('tracking_number', sa.String(length=64), nullable=True),
    sa.Column('destination', sa.String(length=128), nullable=True),
    sa.Column('truck_model', sa.String(length=64), nullable=True),
    sa.Column('capacity_tons', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trucks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trucks_container_number'), ['container_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_trucks_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trucks_driver_name'), ['driver_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_trucks_tracking_number'), ['tracking_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_trucks_truck_number'), ['truck_number'], unique=True)

    op.create_table('bol_records',
    sa.Column('bol_number', sa.String(length=64), nullable=False),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin', sa.String(length=128), nullable=False),
    sa.Column('destination', sa.String(length=128), nullable=True),
    sa.Column('border_station', sa.String(length=128), nullable=False),
    sa.Column('driver_name', sa.String(length=128), nullable=False),
    sa.Column('father_name', sa.String(length=128), nullable=True),
    sa.Column('driver_rent', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('carton_count', sa.Integer(), nullable=False),
    sa.Column('gross_weight_kg', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('net_weight_kg', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('cargo_description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('freight_fee', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('demurrage_fee', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('documentation_fee', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('shipper_name', sa.String(length=200), nullable=True),
    sa.Column('consignee_name', sa.String(length=200), nullable=True),
    sa.Column('notify_party_name', sa.String(length=200), nullable=True),
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('shipper_id', sa.String(length=36), nullable=True),
    sa.Column('consignee_id', sa.String(length=36), nullable=True),
    sa.Column('notify_party_id', sa.String(length=36), nullable=True),
    sa.Column('driver_id', sa.String(length=36), nullable=True),
    sa.Column('truck_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['consignee_id'], ['consignees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['notify_party_id'], ['notify_parties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shipper_id'], ['shippers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bol_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bol_records_bol_number'), ['bol_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_bol_records_border_station'), ['border_station'], unique=False)
        batch_op.create_index(batch_op.f('ix_bol_records_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bol_records_consignee_id'), ['consignee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bol_records_consignee_name'), ['consignee_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_bol_records_destination'), ['destination'], unique=False)
        batch_op.create_index(batch_op.f('ix_bol_records_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bol_records_driver_name'), ['driver_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_bol_records_issue_date'), ['issue_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_bol_records_notify_party_id'), ['notify_party_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bol_records_notify_party_name'), ['notify_party_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_bol_records_origin'), ['origin'], unique=False)
        batch_op.create_index(batch_op.f('ix_bol_records_shipper_id'), ['shipper_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bol_records_shipper_name'), ['shipper_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_bol_records_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bol_records_truck_id'), ['truck_id'], unique=False)

    op.create_table('bol_items',
    sa.Column('bol_id', sa.String(length=36), nullable=False),
    sa.Column('commodity_id', sa.String(length=36), nullable=True),
    sa.Column('item_description', sa.String(length=255), nullable=False),
    sa.Column('carton_count', sa.Integer(), nullable=False),
    sa.Column('gross_weight_kg', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('net_weight_kg', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('volume_cbm', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('package_type', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bol_id'], ['bol_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bol_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bol_items_bol_id'), ['bol_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bol_items_commodity_id'), ['commodity_id'], unique=False)

    op.create_table('expenses',
    sa.Column('expense_number', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('expense_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bol_id', sa.String(length=36), nullable=True),
    sa.Column('paid_to', sa.String(length=160), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bol_id'], ['bol_records.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_bol_id'), ['bol_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_expense_date'), ['expense_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_expense_number'), ['expense_number'], unique=True)

    op.create_table('invoices',
    sa.Column('invoice_number', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('customer_name', sa.String(length=160), nullable=False),
    sa.Column('bol_id', sa.String(length=36), nullable=True),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('freight_fee', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('demurrage_fee', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('documentation_fee', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bol_id'], ['bol_records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_bol_id'), ['bol_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_customer_name'), ['customer_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_invoice_number'), ['invoice_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_invoices_issue_date'), ['issue_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_status'), ['status'], unique=False)

    op.create_table('phytosanitary_certificates',
    sa.Column('certificate_number', sa.String(length=64), nullable=False),
    sa.Column('bol_id', sa.String(length=36), nullable=True),
    sa.Column('issuing_authority', sa.String(length=160), nullable=False),
    sa.Column('inspection_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiration_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('treatments_applied', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bol_id'], ['bol_records.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('phytosanitary_certificates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_phytosanitary_certificates_bol_id'), ['bol_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_phytosanitary_certificates_certificate_number'), ['certificate_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_phytosanitary_certificates_status'), ['status'], unique=False)

    op.create_table('shipments',
    sa.Column('tracking_number', sa.String(length=64), nullable=False),
    sa.Column('reference_number', sa.String(length=64), nullable=True),
    sa.Column('bol_id', sa.String(length=36), nullable=True),
    sa.Column('bol_number', sa.String(length=64), nullable=True),
    sa.Column('origin', sa.String(length=128), nullable=False),
    sa.Column('destination', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('carrier', sa.String(length=128), nullable=True),
    sa.Column('departure_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrival_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('route_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bol_id'], ['bol_records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipments_arrival_date'), ['arrival_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_bol_id'), ['bol_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_bol_number'), ['bol_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_departure_date'), ['departure_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_destination'), ['destination'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_origin'), ['origin'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_reference_number'), ['reference_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_tracking_number'), ['tracking_number'], unique=True)

    op.create_table('transit_papers',
    sa.Column('transit_paper_number', sa.String(length=64), nullable=False),
    sa.Column('bol_id', sa.String(length=36), nullable=True),
    sa.Column('border_station', sa.String(length=128), nullable=False),
    sa.Column('customs_declaration_no', sa.String(length=64), nullable=True),
    sa.Column('entry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bol_id'], ['bol_records.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transit_papers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transit_papers_bol_id'), ['bol_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transit_papers_border_station'), ['border_station'], unique=False)
        batch_op.create_index(batch_op.f('ix_transit_papers_customs_declaration_no'), ['customs_declaration_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_transit_papers_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_transit_papers_transit_paper_number'), ['transit_paper_number'], unique=True)

    op.create_table('containers',
    sa.Column('container_number', sa.String(length=64), nullable=False),
    sa.Column('container_type', sa.String(length=64), nullable=False),
    sa.Column('seal_number', sa.String(length=64), nullable=True),
    sa.Column('tare_weight_kg', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('max_payload_kg', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('bol_id', sa.String(length=36), nullable=True),
    sa.Column('shipment_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bol_id'], ['bol_records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('containers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_containers_bol_id'), ['bol_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_containers_container_number'), ['container_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_containers_container_type'), ['container_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_containers_shipment_id'), ['shipment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_containers_status'), ['status'], unique=False)

    op.create_table('discounts',
    sa.Column('invoice_id', sa.String(length=36), nullable=True),
    sa.Column('bol_id', sa.String(length=36), nullable=True),
    sa.Column('discount_type', sa.String(length=32), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('authorized_by', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bol_id'], ['bol_records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discounts_bol_id'), ['bol_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discounts_invoice_id'), ['invoice_id'], unique=False)

    op.create_table('documents',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('document_type', sa.String(length=64), nullable=False),
    sa.Column('bol_id', sa.String(length=36), nullable=True),
    sa.Column('shipment_id', sa.String(length=36), nullable=True),
    sa.Column('invoice_id', sa.String(length=36), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bol_id'], ['bol_records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_bol_id'), ['bol_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_document_type'), ['document_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_shipment_id'), ['shipment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_title'), ['title'], unique=False)

    op.create_table('freight_charges',
    sa.Column('bol_id', sa.String(length=36), nullable=True),
    sa.Column('shipment_id', sa.String(length=36), nullable=True),
    sa.Column('charge_type', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('is_prepaid', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bol_id'], ['bol_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('freight_charges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_freight_charges_bol_id'), ['bol_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_freight_charges_shipment_id'), ['shipment_id'], unique=False)

    op.create_table('invoice_items',
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('fee_category', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_items_invoice_id'), ['invoice_id'], unique=False)

    op.create_table('ledger_records',
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('account_name', sa.String(length=160), nullable=False),
    sa.Column('transaction_date', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('debit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('fee_type', sa.String(length=32), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('reference_id', sa.String(length=64), nullable=True),
    sa.Column('ledger_account_id', sa.String(length=36), nullable=True),
    sa.Column('bol_id', sa.String(length=36), nullable=True),
    sa.Column('invoice_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bol_id'], ['bol_records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ledger_account_id'], ['ledgers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ledger_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_records_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_records_bol_id'), ['bol_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_records_fee_type'), ['fee_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_records_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_records_ledger_account_id'), ['ledger_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_records_reference_id'), ['reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_records_transaction_date'), ['transaction_date'], unique=False)

    op.create_table('packing_lists',
    sa.Column('packing_list_number', sa.String(length=64), nullable=False),
    sa.Column('bol_id', sa.String(length=36), nullable=True),
    sa.Column('shipment_id', sa.String(length=36), nullable=True),
    sa.Column('total_packages', sa.Integer(), nullable=False),
    sa.Column('total_gross_weight_kg', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_net_weight_kg', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_volume_cbm', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bol_id'], ['bol_records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('packing_lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_packing_lists_bol_id'), ['bol_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_packing_lists_packing_list_number'), ['packing_list_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_packing_lists_shipment_id'), ['shipment_id'], unique=False)

    op.create_table('payments',
    sa.Column('payment_number', sa.String(length=64), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('payment_method', sa.String(length=64), nullable=False),
    sa.Column('reference_no', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_payment_date'), ['payment_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_payment_number'), ['payment_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_payments_reference_no'), ['reference_no'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_reference_no'))
        batch_op.drop_index(batch_op.f('ix_payments_payment_number'))
        batch_op.drop_index(batch_op.f('ix_payments_payment_date'))
        batch_op.drop_index(batch_op.f('ix_payments_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_payments_customer_id'))

    op.drop_table('payments')
    with op.batch_alter_table('packing_lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_packing_lists_shipment_id'))
        batch_op.drop_index(batch_op.f('ix_packing_lists_packing_list_number'))
        batch_op.drop_index(batch_op.f('ix_packing_lists_bol_id'))

    op.drop_table('packing_lists')
    with op.batch_alter_table('ledger_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_records_transaction_date'))
        batch_op.drop_index(batch_op.f('ix_ledger_records_reference_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_records_ledger_account_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_records_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_records_fee_type'))
        batch_op.drop_index(batch_op.f('ix_ledger_records_bol_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_records_account_id'))

    op.drop_table('ledger_records')
    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_items_invoice_id'))

    op.drop_table('invoice_items')
    with op.batch_alter_table('freight_charges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_freight_charges_shipment_id'))
        batch_op.drop_index(batch_op.f('ix_freight_charges_bol_id'))

    op.drop_table('freight_charges')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_title'))
        batch_op.drop_index(batch_op.f('ix_documents_shipment_id'))
        batch_op.drop_index(batch_op.f('ix_documents_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_documents_document_type'))
        batch_op.drop_index(batch_op.f('ix_documents_bol_id'))

    op.drop_table('documents')
    with op.batch_alter_table('discounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discounts_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_discounts_bol_id'))

    op.drop_table('discounts')
    with op.batch_alter_table('containers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_containers_status'))
        batch_op.drop_index(batch_op.f('ix_containers_shipment_id'))
        batch_op.drop_index(batch_op.f('ix_containers_container_type'))
        batch_op.drop_index(batch_op.f('ix_containers_container_number'))
        batch_op.drop_index(batch_op.f('ix_containers_bol_id'))

    op.drop_table('containers')
    with op.batch_alter_table('transit_papers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transit_papers_transit_paper_number'))
        batch_op.drop_index(batch_op.f('ix_transit_papers_status'))
        batch_op.drop_index(batch_op.f('ix_transit_papers_customs_declaration_no'))
        batch_op.drop_index(batch_op.f('ix_transit_papers_border_station'))
        batch_op.drop_index(batch_op.f('ix_transit_papers_bol_id'))

    op.drop_table('transit_papers')
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipments_tracking_number'))
        batch_op.drop_index(batch_op.f('ix_shipments_status'))
        batch_op.drop_index(batch_op.f('ix_shipments_reference_number'))
        batch_op.drop_index(batch_op.f('ix_shipments_origin'))
        batch_op.drop_index(batch_op.f('ix_shipments_destination'))
        batch_op.drop_index(batch_op.f('ix_shipments_departure_date'))
        batch_op.drop_index(batch_op.f('ix_shipments_bol_number'))
        batch_op.drop_index(batch_op.f('ix_shipments_bol_id'))
        batch_op.drop_index(batch_op.f('ix_shipments_arrival_date'))

    op.drop_table('shipments')
    with op.batch_alter_table('phytosanitary_certificates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phytosanitary_certificates_status'))
        batch_op.drop_index(batch_op.f('ix_phytosanitary_certificates_certificate_number'))
        batch_op.drop_index(batch_op.f('ix_phytosanitary_certificates_bol_id'))

    op.drop_table('phytosanitary_certificates')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_status'))
        batch_op.drop_index(batch_op.f('ix_invoices_issue_date'))
        batch_op.drop_index(batch_op.f('ix_invoices_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_invoices_due_date'))
        batch_op.drop_index(batch_op.f('ix_invoices_customer_name'))
        batch_op.drop_index(batch_op.f('ix_invoices_customer_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_bol_id'))

    op.drop_table('invoices')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_expense_number'))
        batch_op.drop_index(batch_op.f('ix_expenses_expense_date'))
        batch_op.drop_index(batch_op.f('ix_expenses_category'))
        batch_op.drop_index(batch_op.f('ix_expenses_bol_id'))

    op.drop_table('expenses')
    with op.batch_alter_table('bol_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bol_items_commodity_id'))
        batch_op.drop_index(batch_op.f('ix_bol_items_bol_id'))

    op.drop_table('bol_items')
    with op.batch_alter_table('bol_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bol_records_truck_id'))
        batch_op.drop_index(batch_op.f('ix_bol_records_status'))
        batch_op.drop_index(batch_op.f('ix_bol_records_shipper_name'))
        batch_op.drop_index(batch_op.f('ix_bol_records_shipper_id'))
        batch_op.drop_index(batch_op.f('ix_bol_records_origin'))
        batch_op.drop_index(batch_op.f('ix_bol_records_notify_party_name'))
        batch_op.drop_index(batch_op.f('ix_bol_records_notify_party_id'))
        batch_op.drop_index(batch_op.f('ix_bol_records_issue_date'))
        batch_op.drop_index(batch_op.f('ix_bol_records_driver_name'))
        batch_op.drop_index(batch_op.f('ix_bol_records_driver_id'))
        batch_op.drop_index(batch_op.f('ix_bol_records_destination'))
        batch_op.drop_index(batch_op.f('ix_bol_records_consignee_name'))
        batch_op.drop_index(batch_op.f('ix_bol_records_consignee_id'))
        batch_op.drop_index(batch_op.f('ix_bol_records_company_id'))
        batch_op.drop_index(batch_op.f('ix_bol_records_border_station'))
        batch_op.drop_index(batch_op.f('ix_bol_records_bol_number'))

    op.drop_table('bol_records')
    with op.batch_alter_table('trucks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trucks_truck_number'))
        batch_op.drop_index(batch_op.f('ix_trucks_tracking_number'))
        batch_op.drop_index(batch_op.f('ix_trucks_driver_name'))
        batch_op.drop_index(batch_op.f('ix_trucks_driver_id'))
        batch_op.drop_index(batch_op.f('ix_trucks_container_number'))

    op.drop_table('trucks')
    with op.batch_alter_table('shippers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shippers_name'))
        batch_op.drop_index(batch_op.f('ix_shippers_company_id'))
        batch_op.drop_index(batch_op.f('ix_shippers_code'))

    op.drop_table('shippers')
    with op.batch_alter_table('consignees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consignees_name'))
        batch_op.drop_index(batch_op.f('ix_consignees_company_id'))
        batch_op.drop_index(batch_op.f('ix_consignees_code'))

    op.drop_table('consignees')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_supplier_type'))
        batch_op.drop_index(batch_op.f('ix_suppliers_supplier_name'))

    op.drop_table('suppliers')
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settings_key'))
        batch_op.drop_index(batch_op.f('ix_settings_category'))

    op.drop_table('settings')
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routes_route_name'))
        batch_op.drop_index(batch_op.f('ix_routes_border_crossing'))

    op.drop_table('routes')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_report_type'))
        batch_op.drop_index(batch_op.f('ix_reports_report_name'))

    op.drop_table('reports')
    with op.batch_alter_table('ports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ports_port_name'))
        batch_op.drop_index(batch_op.f('ix_ports_port_code'))
        batch_op.drop_index(batch_op.f('ix_ports_country'))

    op.drop_table('ports')
    with op.batch_alter_table('notify_parties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notify_parties_name'))

    op.drop_table('notify_parties')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_location_name'))
        batch_op.drop_index(batch_op.f('ix_locations_location_code'))
        batch_op.drop_index(batch_op.f('ix_locations_city'))

    op.drop_table('locations')
    with op.batch_alter_table('ledgers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledgers_account_type'))
        batch_op.drop_index(batch_op.f('ix_ledgers_account_name'))
        batch_op.drop_index(batch_op.f('ix_ledgers_account_code'))

    op.drop_table('ledgers')
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drivers_passport_number'))
        batch_op.drop_index(batch_op.f('ix_drivers_national_id'))
        batch_op.drop_index(batch_op.f('ix_drivers_license_number'))
        batch_op.drop_index(batch_op.f('ix_drivers_driver_name'))

    op.drop_table('drivers')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_customer_type'))
        batch_op.drop_index(batch_op.f('ix_customers_customer_name'))

    op.drop_table('customers')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_company_name'))
        batch_op.drop_index(batch_op.f('ix_companies_code'))

    op.drop_table('companies')
    with op.batch_alter_table('commodities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commodities_hs_code'))
        batch_op.drop_index(batch_op.f('ix_commodities_commodity_name'))
        batch_op.drop_index(batch_op.f('ix_commodities_category'))

    op.drop_table('commodities')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_client_name'))
        batch_op.drop_index(batch_op.f('ix_clients_account_number'))

    op.drop_table('clients')
    with op.batch_alter_table('backups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backups_status'))
        batch_op.drop_index(batch_op.f('ix_backups_backup_filename'))

    op.drop_table('backups')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index('ix_audit_logs_created_at')
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_linked_type'))
        batch_op.drop_index(batch_op.f('ix_attachments_linked_id'))
        batch_op.drop_index('ix_attachment_link')

    op.drop_table('attachments')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_name'))
        batch_op.drop_index(batch_op.f('ix_agents_border_station'))
        batch_op.drop_index(batch_op.f('ix_agents_agent_type'))

    op.drop_table('agents')
    # ### end Alembic commands ###
