import { PermissionItem, RoleDefinition, ApprovalRule } from "./rbac-types"

export const ALL_PERMISSIONS: PermissionItem[] = [
  // 1. BOL PERMISSIONS
  { id: "p-bol-1", permission_key: "bol_view", name: "View Bill of Lading", nameFa: "مشاهده بارنامه", description: "View BOL records and cargo details", category: "BOL" },
  { id: "p-bol-2", permission_key: "bol_create", name: "Create Bill of Lading", nameFa: "ثبت بارنامه جدید", description: "Create and publish new BOLs", category: "BOL" },
  { id: "p-bol-3", permission_key: "bol_edit", name: "Edit Bill of Lading", nameFa: "ویرایش بارنامه", description: "Modify existing operational BOL details", category: "BOL" },
  { id: "p-bol-4", permission_key: "bol_archive", name: "Archive Bill of Lading", nameFa: "آرشیو بارنامه", description: "Archive or soft-delete inactive BOLs", category: "BOL" },
  { id: "p-bol-5", permission_key: "bol_delete_draft", name: "Delete Draft BOL", nameFa: "حذف پیش‌نویس بارنامه", description: "Permanently discard uncommitted draft BOLs", category: "BOL" },
  { id: "p-bol-6", permission_key: "bol_duplicate", name: "Duplicate BOL", nameFa: "کپی/تکرار بارنامه", description: "Clone an existing BOL as a new template", category: "BOL" },
  { id: "p-bol-7", permission_key: "bol_bulk_create", name: "Bulk Create BOLs", nameFa: "ثبت دسته‌جمعی بارنامه", description: "Create multi-container BOL batches", category: "BOL" },
  { id: "p-bol-8", permission_key: "bol_bulk_update", name: "Bulk Update BOLs", nameFa: "بروزرسانی گروهی بارنامه", description: "Batch modify statuses or border stations", category: "BOL" },
  { id: "p-bol-9", permission_key: "bol_print", name: "Print Bill of Lading", nameFa: "چاپ فیزیکی بارنامه", description: "Print standard physical A4 shipping sheets", category: "BOL" },
  { id: "p-bol-10", permission_key: "bol_pdf", name: "Generate PDF", nameFa: "تولید PDF رسمی بارنامه", description: "Download high-res official vector PDF manifests", category: "BOL" },
  { id: "p-bol-11", permission_key: "bol_release_client", name: "Release to Client", nameFa: "انتشار برای مشتری", description: "Make BOL visible in customer portal", category: "BOL" },

  // 2. SHIPMENT PERMISSIONS
  { id: "p-shp-1", permission_key: "shipment_view", name: "View Shipments", nameFa: "مشاهده محموله‌ها", description: "Browse active operational shipments", category: "SHIPMENTS" },
  { id: "p-shp-2", permission_key: "shipment_create", name: "Create Shipment", nameFa: "ایجاد محموله", description: "Initiate cargo transit bookings", category: "SHIPMENTS" },
  { id: "p-shp-3", permission_key: "shipment_edit", name: "Edit Shipment", nameFa: "ویرایش محموله", description: "Update cargo quantities, containers, trucks", category: "SHIPMENTS" },
  { id: "p-shp-4", permission_key: "shipment_archive", name: "Archive Shipment", nameFa: "آرشیو محموله", description: "Archive completed transport cycles", category: "SHIPMENTS" },
  { id: "p-shp-5", permission_key: "shipment_bulk_import", name: "Bulk Import Shipments", nameFa: "واردات گروهی محموله", description: "Upload multi-row manifest spreadsheets", category: "SHIPMENTS" },
  { id: "p-shp-6", permission_key: "shipment_bulk_update", name: "Bulk Update Shipments", nameFa: "بروزرسانی انبوه محموله‌ها", description: "Update multiple shipment status in one run", category: "SHIPMENTS" },

  // 3. TRACKING PERMISSIONS
  { id: "p-trk-1", permission_key: "tracking_view", name: "View Tracking", nameFa: "مشاهده رهگیری", description: "View transit control tower & checkpoints", category: "TRACKING" },
  { id: "p-trk-2", permission_key: "tracking_update", name: "Update Tracking", nameFa: "ثبت وضعیت مکانی", description: "Post milestone checkpoints and border transit events", category: "TRACKING" },
  { id: "p-trk-3", permission_key: "tracking_bulk_update", name: "Bulk Update Tracking", nameFa: "بروزرسانی گروهی موقعیت", description: "Batch update border clearance stages", category: "TRACKING" },
  { id: "p-trk-4", permission_key: "tracking_edit_history", name: "Edit Tracking History", nameFa: "ویرایش تاریخچه رهگیری", description: "Correct chronological event records", category: "TRACKING" },
  { id: "p-trk-5", permission_key: "tracking_correct_event", name: "Correct Checkpoint", nameFa: "اصلاح رویداد مرزی", description: "Void or replace invalid scan logs", category: "TRACKING" },
  { id: "p-trk-6", permission_key: "tracking_view_internal_notes", name: "Internal Tracking Notes", nameFa: "یادداشت‌های محرمانه عملیات", description: "Access private transit and driver notes", category: "TRACKING" },

  // 4. DOCUMENT PERMISSIONS
  { id: "p-doc-1", permission_key: "documents_view", name: "View Documents", nameFa: "مشاهده اسناد", description: "Inspect shipping document vault", category: "DOCUMENTS" },
  { id: "p-doc-2", permission_key: "documents_create", name: "Create Document", nameFa: "تهیه سند جدید", description: "Draft Commercial Invoices, CMRs, Packing Lists", category: "DOCUMENTS" },
  { id: "p-doc-3", permission_key: "documents_edit_draft", name: "Edit Draft Document", nameFa: "ویرایش پیش‌نویس سند", description: "Update unfinalized paperwork templates", category: "DOCUMENTS" },
  { id: "p-doc-4", permission_key: "documents_finalize", name: "Finalize Document", nameFa: "نهایی‌سازی سند", description: "Lock document draft against casual changes", category: "DOCUMENTS" },
  { id: "p-doc-5", permission_key: "documents_issue", name: "Issue Official Document", nameFa: "صدور رسمی سند", description: "Sign, seal, and issue official stamped paperwork", category: "DOCUMENTS" },
  { id: "p-doc-6", permission_key: "documents_revise", name: "Revise Issued Document", nameFa: "اصلاح سند صادرشده", description: "Generate stamped revision of official document", category: "DOCUMENTS" },
  { id: "p-doc-7", permission_key: "documents_void", name: "Void Document", nameFa: "ابطال سند", description: "Cancel and void issued trade paperwork", category: "DOCUMENTS" },
  { id: "p-doc-8", permission_key: "documents_release_client", name: "Release to Client", nameFa: "ارسال سند به پرتال مشتری", description: "Authorize client download in portal", category: "DOCUMENTS" },
  { id: "p-doc-9", permission_key: "documents_download", name: "Download Documents", nameFa: "دانلود اسناد", description: "Save merged PDF trade packets", category: "DOCUMENTS" },
  { id: "p-doc-10", permission_key: "documents_bulk_generate", name: "Bulk Generate Documents", nameFa: "تولید دسته‌جمعی اسناد", description: "Batch create documents for multiple shipments", category: "DOCUMENTS" },

  // 5. ACCOUNTING PERMISSIONS
  { id: "p-acc-1", permission_key: "accounting_view", name: "View Accounting", nameFa: "مشاهده حسابداری", description: "Read financial transaction statements", category: "ACCOUNTING" },
  { id: "p-acc-2", permission_key: "accounting_dashboard", name: "Accounting Dashboard", nameFa: "داشبورد مالی", description: "Access comprehensive financial control center", category: "ACCOUNTING" },
  { id: "p-acc-3", permission_key: "accounting_create_transaction", name: "Create Draft Transaction", nameFa: "ایجاد تراکنش مالی", description: "Draft debits, credits, and demurrage entries", category: "ACCOUNTING" },
  { id: "p-acc-4", permission_key: "accounting_edit_draft_transaction", name: "Edit Draft Transaction", nameFa: "ویرایش پیش‌نویس مالی", description: "Modify unposted financial drafts", category: "ACCOUNTING" },
  { id: "p-acc-5", permission_key: "accounting_post_transaction", name: "Post Financial Transaction", nameFa: "ثبت قطعی در دفتر کل", description: "Commit transaction permanently to ledger balance", category: "ACCOUNTING" },
  { id: "p-acc-6", permission_key: "accounting_reverse_transaction", name: "Reverse Transaction", nameFa: "برگشت تراکنش مالی", description: "Post compensating reversal with audit reason", category: "ACCOUNTING" },
  { id: "p-acc-7", permission_key: "accounting_view_audit", name: "View Financial Audit", nameFa: "مشاهده گزارش حسابرسی", description: "Inspect transaction immutability and history", category: "ACCOUNTING" },

  // 6. LEDGER PERMISSIONS
  { id: "p-led-1", permission_key: "ledger_view", name: "View Ledgers", nameFa: "مشاهده دفاتر حساب", description: "Browse client and supplier accounts", category: "LEDGERS" },
  { id: "p-led-2", permission_key: "ledger_create", name: "Create Account Ledger", nameFa: "افتتاح حساب جدید", description: "Create customer or carrier ledger profile", category: "LEDGERS" },
  { id: "p-led-3", permission_key: "ledger_edit", name: "Edit Account Ledger", nameFa: "ویرایش حساب دفتر", description: "Update ledger name, currency, or contact", category: "LEDGERS" },
  { id: "p-led-4", permission_key: "ledger_view_balance", name: "View Balances", nameFa: "مشاهده مانده حساب", description: "View net debit/credit balance summaries", category: "LEDGERS" },
  { id: "p-led-5", permission_key: "ledger_view_transactions", name: "View Transactions", nameFa: "مشاهده گردش حساب", description: "Audit chronological transaction line items", category: "LEDGERS" },
  { id: "p-led-6", permission_key: "ledger_export", name: "Export Ledger", nameFa: "خروجی اکسل/PDF دفتر", description: "Export bilingual A4 statement of accounts", category: "LEDGERS" },
  { id: "p-led-7", permission_key: "ledger_merge_accounts", name: "Merge Ledger Accounts", nameFa: "ادغام دفاتر حساب", description: "Combine redundant customer ledgers", category: "LEDGERS" },
  { id: "p-led-8", permission_key: "ledger_archive", name: "Archive Account", nameFa: "بستن/آرشیو حساب", description: "Deactivate settled client ledgers", category: "LEDGERS" },

  // 7. CUSTOMERS
  { id: "p-cus-1", permission_key: "customer_view", name: "View Customers", nameFa: "مشاهده مشتریان", description: "Browse customer company directory", category: "CUSTOMERS" },
  { id: "p-cus-2", permission_key: "customer_create", name: "Create Customer", nameFa: "ثبت مشتری جدید", description: "Add new shippers, consignees, and clients", category: "CUSTOMERS" },
  { id: "p-cus-3", permission_key: "customer_edit", name: "Edit Customer", nameFa: "ویرایش مشخصات مشتری", description: "Update contact person, phone, credit terms", category: "CUSTOMERS" },
  { id: "p-cus-4", permission_key: "customer_archive", name: "Archive Customer", nameFa: "آرشیو مشتری", description: "Deactivate inactive customer records", category: "CUSTOMERS" },

  // 8. SUPPLIERS
  { id: "p-sup-1", permission_key: "supplier_view", name: "View Suppliers", nameFa: "مشاهده تأمین‌کنندگان", description: "Inspect shipping lines, trucking agents, and customs brokers", category: "SUPPLIERS" },
  { id: "p-sup-2", permission_key: "supplier_create", name: "Create Supplier", nameFa: "ثبت تأمین‌کننده جدید", description: "Register new vendor or transport carrier", category: "SUPPLIERS" },
  { id: "p-sup-3", permission_key: "supplier_edit", name: "Edit Supplier", nameFa: "ویرایش تأمین‌کننده", description: "Modify vendor terms and bank routing details", category: "SUPPLIERS" },
  { id: "p-sup-4", permission_key: "supplier_archive", name: "Archive Supplier", nameFa: "آرشیو تأمین‌کننده", description: "Deactivate obsolete vendor accounts", category: "SUPPLIERS" },

  // 9. PAYMENTS
  { id: "p-pay-1", permission_key: "payment_view", name: "View Payments", nameFa: "مشاهده دریافتی‌ها", description: "Browse customer payment receipts", category: "PAYMENTS" },
  { id: "p-pay-2", permission_key: "payment_create_draft", name: "Draft Payment", nameFa: "ثبت پیش‌نویس پرداخت", description: "Record incoming client wire receipts", category: "PAYMENTS" },
  { id: "p-pay-3", permission_key: "payment_confirm", name: "Confirm Payment", nameFa: "تایید و وصول پرداخت", description: "Commit payment and reduce customer debit balance", category: "PAYMENTS" },
  { id: "p-pay-4", permission_key: "payment_edit", name: "Edit Payment", nameFa: "ویرایش رسید پرداخت", description: "Modify reference number or bank slip data", category: "PAYMENTS" },
  { id: "p-pay-5", permission_key: "payment_reverse", name: "Reverse Payment", nameFa: "برگشت پرداخت مشتری", description: "Post bounced check or bank transfer reversal", category: "PAYMENTS" },
  { id: "p-pay-6", permission_key: "payment_allocate", name: "Allocate Payment", nameFa: "تخصیص به فاکتورها", description: "Apply receipts against specific BOL invoices", category: "PAYMENTS" },
  { id: "p-pay-7", permission_key: "payment_upload_attachment", name: "Upload Bank Slips", nameFa: "آپلود فیش بانکی", description: "Attach deposit slips and swift proofs", category: "PAYMENTS" },

  // 10. SUPPLIER COSTS
  { id: "p-cst-1", permission_key: "cost_view", name: "View Supplier Costs", nameFa: "مشاهده هزینه‌های باربری", description: "View freight, port, and border transit costs", category: "SUPPLIER_COSTS" },
  { id: "p-cst-2", permission_key: "cost_create_draft", name: "Draft Supplier Cost", nameFa: "ثبت پیش‌نویس هزینه", description: "Enter estimated carrier freight and driver rents", category: "SUPPLIER_COSTS" },
  { id: "p-cst-3", permission_key: "cost_edit", name: "Edit Supplier Cost", nameFa: "ویرایش هزینه", description: "Modify unapproved expense items", category: "SUPPLIER_COSTS" },
  { id: "p-cst-4", permission_key: "cost_submit", name: "Submit Cost for Approval", nameFa: "ارسال هزینه جهت تایید", description: "Request supervisor sign-off on expense bills", category: "SUPPLIER_COSTS" },
  { id: "p-cst-5", permission_key: "cost_approve", name: "Approve Supplier Cost", nameFa: "تایید هزینه باربری", description: "Approve supplier expense for accounting posting", category: "SUPPLIER_COSTS" },
  { id: "p-cst-6", permission_key: "cost_post", name: "Post Cost to Ledger", nameFa: "ثبت قطعی در بستانکار", description: "Credit vendor payable account permanently", category: "SUPPLIER_COSTS" },
  { id: "p-cst-7", permission_key: "cost_reverse", name: "Reverse Cost", nameFa: "برگشت/اصلاح هزینه", description: "Void incorrectly booked supplier bills", category: "SUPPLIER_COSTS" },

  // 11. SUPPLIER PAYMENTS
  { id: "p-spay-1", permission_key: "supplier_payment_view", name: "View Supplier Payments", nameFa: "مشاهده پرداختی به شرکت‌ها", description: "Inspect payouts to drivers, agents, shipping lines", category: "SUPPLIER_PAYMENTS" },
  { id: "p-spay-2", permission_key: "supplier_payment_create", name: "Create Supplier Payment", nameFa: "ایجاد پرداخت به تأمین‌کننده", description: "Prepare disbursement draft to vendor", category: "SUPPLIER_PAYMENTS" },
  { id: "p-spay-3", permission_key: "supplier_payment_approve", name: "Approve Supplier Payment", nameFa: "تایید خروج وجه به شرکت‌ها", description: "Authorize wire or cash payout to vendor", category: "SUPPLIER_PAYMENTS" },
  { id: "p-spay-4", permission_key: "supplier_payment_post", name: "Post Supplier Payment", nameFa: "ثبت قطعی پرداخت به تأمین‌کننده", description: "Debit vendor payable account in ledger", category: "SUPPLIER_PAYMENTS" },
  { id: "p-spay-5", permission_key: "supplier_payment_reverse", name: "Reverse Supplier Payment", nameFa: "برگشت پرداخت به شرکت", description: "Post refund or canceled wire transfer", category: "SUPPLIER_PAYMENTS" },

  // 12. PROFITABILITY
  { id: "p-prf-1", permission_key: "profit_view", name: "View Profitability", nameFa: "مشاهده سود و زیان", description: "View gross profit, net profit, and profit margins", category: "PROFITABILITY" },
  { id: "p-prf-2", permission_key: "margin_view", name: "View Margin %", nameFa: "مشاهده درصد مارجین", description: "View profit percentage metrics per route and container", category: "PROFITABILITY" },
  { id: "p-prf-3", permission_key: "cost_view_internal", name: "View Internal Company Costs", nameFa: "مشاهده هزینه‌های مخفی/داخلی", description: "Inspect confidential cost breakdowns and markups", category: "PROFITABILITY" },
  { id: "p-prf-4", permission_key: "customer_profitability_view", name: "Customer Profitability", nameFa: "سودآوری به تفکیک مشتری", description: "Analyze customer-level margin performance", category: "PROFITABILITY" },
  { id: "p-prf-5", permission_key: "route_profitability_view", name: "Route Profitability", nameFa: "سودآوری به تفکیک مسیر", description: "Analyze corridor margins (Dubai-Kabul, Abbas-Herat)", category: "PROFITABILITY" },
  { id: "p-prf-6", permission_key: "management_profit_report", name: "Management P&L Report", nameFa: "گزارش جامع مدیریت مالی", description: "Executive profit & loss summaries and KPIs", category: "PROFITABILITY" },

  // 13. IMPORT / EXPORT
  { id: "p-imp-1", permission_key: "import_excel", name: "Import Excel", nameFa: "وارد کردن اکسل", description: "Upload shipments and ledgers via Excel", category: "IMPORT_EXPORT" },
  { id: "p-imp-2", permission_key: "import_json", name: "Import JSON", nameFa: "وارد کردن فایل JSON", description: "Restore data from JSON snapshots", category: "IMPORT_EXPORT" },
  { id: "p-imp-3", permission_key: "bulk_import", name: "Bulk Import Tool", nameFa: "ابزار ورود دسته‌جمعی", description: "Access high-speed multi-entity bulk importer", category: "IMPORT_EXPORT" },
  { id: "p-imp-4", permission_key: "import_preview", name: "Preview Import Data", nameFa: "پیش‌نمایش واردات", description: "Validate columns and preview row reconciliation", category: "IMPORT_EXPORT" },
  { id: "p-imp-5", permission_key: "import_execute", name: "Execute Bulk Import", nameFa: "اجرای ورود اطلاعات", description: "Commit hundreds of rows to active database", category: "IMPORT_EXPORT" },
  { id: "p-imp-6", permission_key: "import_rollback", name: "Rollback Import Batch", nameFa: "بازگردانی بسته وارد شده", description: "Undo flawed import runs cleanly", category: "IMPORT_EXPORT" },
  { id: "p-imp-7", permission_key: "import_reconciliation", name: "Import Reconciliation", nameFa: "مغایرت‌گیری واردات", description: "Match imported shipments against ledgers", category: "IMPORT_EXPORT" },

  // 14. BACKUP
  { id: "p-bak-1", permission_key: "backup_create", name: "Create Backup", nameFa: "ایجاد نسخه پشتیبان", description: "Snapshot database to local and cloud storage", category: "BACKUP" },
  { id: "p-bak-2", permission_key: "backup_download", name: "Download Backup", nameFa: "دانلود فایل پشتیبان", description: "Save compressed snapshot archive file", category: "BACKUP" },
  { id: "p-bak-3", permission_key: "backup_restore", name: "Restore Backup", nameFa: "بازیابی نسخه پشتیبان", description: "Overwrite system state with historical backup", category: "BACKUP" },
  { id: "p-bak-4", permission_key: "backup_delete", name: "Delete Backup", nameFa: "حذف فایل پشتیبان", description: "Permanently delete obsolete snapshot archives", category: "BACKUP" },

  // 15. CLIENT PORTAL
  { id: "p-clp-1", permission_key: "client_user_view", name: "View Client Users", nameFa: "مشاهده کاربران مشتری", description: "Browse external client portal accounts", category: "CLIENT_PORTAL" },
  { id: "p-clp-2", permission_key: "client_user_invite", name: "Invite Client User", nameFa: "دعوت کاربر مشتری جدید", description: "Generate portal activation credentials", category: "CLIENT_PORTAL" },
  { id: "p-clp-3", permission_key: "client_user_suspend", name: "Suspend Client User", nameFa: "تعلیق دسترسی مشتری", description: "Block portal login for a customer account", category: "CLIENT_PORTAL" },
  { id: "p-clp-4", permission_key: "client_access_manage", name: "Manage Client Scopes", nameFa: "مدیریت دسترسی شرکت مشتری", description: "Assign BOLs and company entities to client accounts", category: "CLIENT_PORTAL" },
  { id: "p-clp-5", permission_key: "client_document_release", name: "Release Documents to Portal", nameFa: "صدور مجوز دانلود اسناد", description: "Authorize client to view and download certificates", category: "CLIENT_PORTAL" },
  { id: "p-clp-6", permission_key: "client_financial_access_manage", name: "Client Financial Toggle", nameFa: "تنظیم دسترسی مالی مشتری", description: "Allow or block client from viewing statement of account", category: "CLIENT_PORTAL" },

  // 16. USERS
  { id: "p-usr-1", permission_key: "user_view", name: "View Staff Users", nameFa: "مشاهده کارمندان", description: "View staff list, departments, and roles", category: "USERS" },
  { id: "p-usr-2", permission_key: "user_create", name: "Create Staff User", nameFa: "ایجاد کاربر کارمند جدید", description: "Register internal operators and accountants", category: "USERS" },
  { id: "p-usr-3", permission_key: "user_edit", name: "Edit User Profile", nameFa: "ویرایش مشخصات کارمند", description: "Update name, department, branch, or contact", category: "USERS" },
  { id: "p-usr-4", permission_key: "user_suspend", name: "Suspend / Deactivate User", nameFa: "تعلیق یا مسدودسازی کاربر", description: "Lock user account without deleting audit history", category: "USERS" },
  { id: "p-usr-5", permission_key: "user_role_assign", name: "Assign User Role", nameFa: "تغییر نقش کارمند", description: "Promote or assign permissions to a staff member", category: "USERS" },
  { id: "p-usr-6", permission_key: "role_create", name: "Create Custom Role", nameFa: "ایجاد نقش سازمانی جدید", description: "Define new staff roles and clone templates", category: "USERS" },
  { id: "p-usr-7", permission_key: "role_edit", name: "Edit Role Permissions", nameFa: "ویرایش اختیارات نقش", description: "Modify role permission matrix checkboxes", category: "USERS" },
  { id: "p-usr-8", permission_key: "permission_manage", name: "Manage Permission Matrix", nameFa: "مدیریت ماتریس اختیارات", description: "Configure system-wide granular security matrix", category: "USERS" },

  // 17. SETTINGS
  { id: "p-set-1", permission_key: "settings_view", name: "View System Settings", nameFa: "مشاهده تنظیمات سامانه", description: "Open system settings and cloud tabs", category: "SETTINGS" },
  { id: "p-set-2", permission_key: "settings_edit", name: "Edit System Settings", nameFa: "ویرایش تنظیمات اصلی", description: "Update company profile, seals, and system defaults", category: "SETTINGS" },
  { id: "p-set-3", permission_key: "accounting_settings", name: "Accounting Settings", nameFa: "تنظیمات مالی و ارزها", description: "Configure exchange rates, default currencies, VAT/demurrage", category: "SETTINGS" },
  { id: "p-set-4", permission_key: "bol_settings", name: "BOL Settings", nameFa: "تنظیمات فرم بارنامه", description: "Configure BOL number prefix, stamp placement, and templates", category: "SETTINGS" },
  { id: "p-set-5", permission_key: "document_settings", name: "Document Settings", nameFa: "تنظیمات صدور اسناد", description: "Manage official stamp logos and signatures", category: "SETTINGS" },
  { id: "p-set-6", permission_key: "tracking_settings", name: "Tracking Settings", nameFa: "تنظیمات رهگیری مرزی", description: "Configure border stations and WhatsApp templates", category: "SETTINGS" },
  { id: "p-set-7", permission_key: "alert_settings", name: "Alert & Notification Rules", nameFa: "تنظیمات هشدارها", description: "Set overdue payment and border transit delay alerts", category: "SETTINGS" },
  { id: "p-set-8", permission_key: "security_settings", name: "Security & Approval Rules", nameFa: "تنظیمات امنیتی و تاییدات", description: "Configure multi-currency approval thresholds & 4-eyes rules", category: "SETTINGS" },
]

export const ALL_PERMISSION_KEYS = ALL_PERMISSIONS.map((p) => p.permission_key)

// Helper to filter keys
const keysFor = (categories: string[], extra: string[] = []): string[] => {
  const matched = ALL_PERMISSIONS.filter((p) => categories.includes(p.category)).map((p) => p.permission_key)
  return Array.from(new Set([...matched, ...extra]))
}

// Canonical Default System Roles
export const DEFAULT_SYSTEM_ROLES: RoleDefinition[] = [
  {
    id: "superadmin",
    name: "Super Admin",
    nameFa: "مدیر ارشد سامانه (دسترسی نامحدود)",
    description: "Complete unrestricted administrative control across all operations, financials, security, and backups.",
    system_role: true,
    active: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    permissions: ALL_PERMISSION_KEYS, // Has all permissions
  },
  {
    id: "admin",
    name: "Administrator",
    nameFa: "مدیر اجرایی و عملیاتی",
    description: "Full operational and financial administration, user management, and configuration (excluding destructive restore).",
    system_role: true,
    active: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    permissions: ALL_PERMISSION_KEYS.filter((k) => k !== "backup_restore" && k !== "permission_manage"),
  },
  {
    id: "management",
    name: "Management / Executive",
    nameFa: "مدیریت ارشد / تصمیم‌گیری مالی",
    description: "Executive dashboards, full profit & margin visibility, and financial approval authority. Gated from routine data entry.",
    system_role: true,
    active: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    permissions: [
      "bol_view", "bol_print", "bol_pdf",
      "shipment_view",
      "tracking_view", "tracking_view_internal_notes",
      "documents_view", "documents_download",
      "accounting_view", "accounting_dashboard", "accounting_view_audit",
      "ledger_view", "ledger_view_balance", "ledger_view_transactions", "ledger_export",
      "customer_view", "supplier_view",
      "payment_view",
      "cost_view", "cost_approve",
      "supplier_payment_view", "supplier_payment_approve",
      "profit_view", "margin_view", "cost_view_internal", "customer_profitability_view", "route_profitability_view", "management_profit_report",
      "backup_create", "backup_download",
      "user_view",
      "settings_view", "security_settings",
    ],
  },
  {
    id: "operations",
    name: "Operations Staff",
    nameFa: "کارشناس عملیات و بارنامه",
    description: "Create and update BOLs, manage containers, assign drivers and border transit routes. Gated from financial approvals and profit.",
    system_role: true,
    active: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    permissions: [
      "bol_view", "bol_create", "bol_edit", "bol_archive", "bol_duplicate", "bol_bulk_create", "bol_bulk_update", "bol_print", "bol_pdf", "bol_release_client",
      "shipment_view", "shipment_create", "shipment_edit", "shipment_archive", "shipment_bulk_import", "shipment_bulk_update",
      "tracking_view", "tracking_update", "tracking_bulk_update", "tracking_edit_history", "tracking_correct_event", "tracking_view_internal_notes",
      "documents_view", "documents_create", "documents_edit_draft", "documents_download",
      "customer_view", "customer_create",
      "supplier_view",
      "cost_create_draft", "cost_submit",
      "import_excel", "bulk_import", "import_preview", "import_execute",
      "settings_view",
    ],
  },
  {
    id: "accounting",
    name: "Accounting & Finance",
    nameFa: "حسابداری و امور مالی",
    description: "Manage client ledgers, invoices, payments, vendor bills, and financial statements. Gated from changing shipment operational transit records.",
    system_role: true,
    active: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    permissions: [
      "bol_view", "bol_print", "bol_pdf",
      "shipment_view",
      "documents_view", "documents_create", "documents_download",
      "accounting_view", "accounting_dashboard", "accounting_create_transaction", "accounting_edit_draft_transaction", "accounting_post_transaction", "accounting_reverse_transaction", "accounting_view_audit",
      "ledger_view", "ledger_create", "ledger_edit", "ledger_view_balance", "ledger_view_transactions", "ledger_export",
      "customer_view", "customer_create", "customer_edit",
      "supplier_view", "supplier_create", "supplier_edit",
      "payment_view", "payment_create_draft", "payment_confirm", "payment_edit", "payment_allocate", "payment_upload_attachment",
      "cost_view", "cost_create_draft", "cost_edit", "cost_submit", "cost_post",
      "supplier_payment_view", "supplier_payment_create", "supplier_payment_post",
      "settings_view", "accounting_settings",
    ],
  },
  {
    id: "documents",
    name: "Documentation Specialist",
    nameFa: "کارشناس اسناد و ترخیص",
    description: "Prepare and finalize Commercial Invoices, Packing Lists, Phyto Certificates, and CMR manifests. Gated from ledger posting and profit data.",
    system_role: true,
    active: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    permissions: [
      "bol_view", "bol_print", "bol_pdf",
      "shipment_view",
      "documents_view", "documents_create", "documents_edit_draft", "documents_finalize", "documents_issue", "documents_revise", "documents_void", "documents_release_client", "documents_download", "documents_bulk_generate",
      "customer_view",
      "supplier_view",
      "settings_view", "document_settings",
    ],
  },
  {
    id: "tracking",
    name: "Tracking Officer",
    nameFa: "مسئول رهگیری و گمرکات",
    description: "Update vehicle checkpoints, border transit milestones, ETA projections, and WhatsApp messages. Gated from accounting and documents.",
    system_role: true,
    active: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    permissions: [
      "bol_view",
      "shipment_view",
      "tracking_view", "tracking_update", "tracking_bulk_update", "tracking_edit_history", "tracking_correct_event",
      "customer_view",
      "settings_view", "tracking_settings",
    ],
  },
  {
    id: "data_entry",
    name: "Data Entry Operator",
    nameFa: "اپراتور ورود اطلاعات",
    description: "Enter draft BOLs, upload manifest spreadsheets, and register contact entities. Gated from posting or approving financial records.",
    system_role: true,
    active: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    permissions: [
      "bol_view", "bol_create", "bol_delete_draft", "bol_duplicate", "bol_print",
      "shipment_view", "shipment_create", "shipment_bulk_import",
      "customer_view", "customer_create",
      "supplier_view", "supplier_create",
      "import_excel", "bulk_import", "import_preview",
    ],
  },
  {
    id: "viewer",
    name: "Read-Only Viewer",
    nameFa: "بیننده عادی (فقط خواندنی)",
    description: "Inspect operational information with zero edit, delete, or posting privileges.",
    system_role: true,
    active: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    permissions: [
      "bol_view", "bol_print",
      "shipment_view",
      "tracking_view",
      "documents_view",
      "customer_view",
      "supplier_view",
    ],
  },
  {
    id: "client",
    name: "Client Portal User",
    nameFa: "مشتری / صاحب کالا",
    description: "Dedicated external portal access strictly scoped to own company shipments, tracking, and released documents.",
    system_role: true,
    active: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    permissions: [
      "bol_view", "bol_print", "bol_pdf",
      "shipment_view",
      "tracking_view",
      "documents_view", "documents_download",
      "ledger_view", "ledger_view_balance", "ledger_view_transactions", "ledger_export",
    ],
  },
]

// Default Multi-Currency Approval Rules
export const DEFAULT_APPROVAL_RULES: ApprovalRule[] = [
  {
    id: "rule-supplier-payment-usd",
    action_type: "supplier_payment_post",
    name: "High-Value Supplier Payment (USD)",
    description: "Supplier disbursements of $10,000 USD or more require Management / Admin authorization.",
    min_amount: 10000,
    currency: "USD",
    requester_roles: ["accounting", "admin"],
    approver_roles: ["management", "superadmin"],
    approvals_required: 1,
    allow_self_approval: false,
    active: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "rule-supplier-payment-aed",
    action_type: "supplier_payment_post",
    name: "High-Value Supplier Payment (AED)",
    description: "Supplier payouts of 36,700 AED or more require Management authorization.",
    min_amount: 36700,
    currency: "AED",
    requester_roles: ["accounting", "admin"],
    approver_roles: ["management", "superadmin"],
    approvals_required: 1,
    allow_self_approval: false,
    active: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "rule-supplier-payment-afn",
    action_type: "supplier_payment_post",
    name: "High-Value Supplier Payment (AFN)",
    description: "Driver rent and border payouts of 500,000 AFN or more require Management authorization.",
    min_amount: 500000,
    currency: "AFN",
    requester_roles: ["accounting", "admin"],
    approver_roles: ["management", "superadmin"],
    approvals_required: 1,
    allow_self_approval: false,
    active: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "rule-payment-reversal",
    action_type: "customer_payment_reversal",
    name: "Customer Payment Reversal",
    description: "Reversing or voiding any recorded customer payment requires Management approval.",
    min_amount: 0,
    currency: "ANY",
    requester_roles: ["accounting", "admin"],
    approver_roles: ["management", "superadmin"],
    approvals_required: 1,
    allow_self_approval: false,
    active: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "rule-ledger-adjustment",
    action_type: "ledger_adjustment_post",
    name: "Manual Ledger Balance Adjustment",
    description: "Manual credit/debit adjustments exceeding $2,500 USD require supervisor review.",
    min_amount: 2500,
    currency: "USD",
    requester_roles: ["accounting"],
    approver_roles: ["management", "admin", "superadmin"],
    approvals_required: 1,
    allow_self_approval: false,
    active: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "rule-account-merge",
    action_type: "account_merge",
    name: "Ledger Account Merge",
    description: "Merging customer accounts requires Admin or Superadmin authorization.",
    min_amount: 0,
    currency: "ANY",
    requester_roles: ["accounting", "admin"],
    approver_roles: ["superadmin"],
    approvals_required: 1,
    allow_self_approval: false,
    active: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "rule-backup-restore",
    action_type: "backup_restore",
    name: "Database Backup Restoration",
    description: "Restoring system database from snapshot requires Superadmin approval.",
    min_amount: 0,
    currency: "ANY",
    requester_roles: ["admin", "superadmin"],
    approver_roles: ["superadmin"],
    approvals_required: 1,
    allow_self_approval: false,
    active: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
]
