/**
 * Sky Ariana Logistics — Default Document Categories & Requirement Rules
 * Phase 14: Document Upload, Automatic Attachment Organization & Digital Shipment Folder
 */

import type { DocumentCategory, DocumentRequirementRule } from "@/lib/types/shipment-file"

export const DEFAULT_DOCUMENT_CATEGORIES: DocumentCategory[] = [
  {
    id: "cat-shipping",
    name: "Shipping Documents",
    name_fa: "اسناد باربری و خطوط کشتیرانی",
    code: "SHIPPING",
    parent_category_id: null,
    description: "Shipping Line Bills of Lading (First Leg, Final, Switch, Master, House), Booking Confirmations, Container Releases, Delivery Orders and VGMs.",
    active: true,
    required_for_route: ["*"],
    required_for_commodity: ["*"],
    client_visible_default: true,
    icon: "Ship",
    color: "blue",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "cat-customs",
    name: "Customs & Transit Documents",
    name_fa: "اسناد گمرکی و ترانزیت",
    code: "CUSTOMS",
    parent_category_id: null,
    description: "Border clearance, transit papers, customs declarations for Afghanistan, Iran, UAE, Turkey, and border duty slips.",
    active: true,
    required_for_route: ["*"],
    required_for_commodity: ["*"],
    client_visible_default: true,
    icon: "ShieldCheck",
    color: "emerald",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "cat-commercial",
    name: "Commercial Trade Documents",
    name_fa: "اسناد تجارتی و فاکتورها",
    code: "COMMERCIAL",
    parent_category_id: null,
    description: "Official Commercial Invoices, itemized Packing Lists, Proforma Invoices, Sales and Purchase Agreements.",
    active: true,
    required_for_route: ["*"],
    required_for_commodity: ["*"],
    client_visible_default: true,
    icon: "FileSpreadsheet",
    color: "indigo",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "cat-certificates",
    name: "Official Certificates",
    name_fa: "گواهی‌نامه‌های رسمی و قرنطین",
    code: "CERTIFICATES",
    parent_category_id: null,
    description: "Phytosanitary, Certificate of Origin, Quarantine, Fumigation, and International Quality Inspection certificates.",
    active: true,
    required_for_route: ["*"],
    required_for_commodity: ["Dry Fruit", "Agricultural", "Foodstuff", "*"],
    client_visible_default: true,
    icon: "Award",
    color: "amber",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "cat-transport",
    name: "Truck & Driver Documents",
    name_fa: "اسناد موتر، راننده و ترانسپورت",
    code: "TRANSPORT",
    parent_category_id: null,
    description: "Truck registration plates, driver license, Tazkira/ID, transport route permits, vehicle insurance records.",
    active: true,
    required_for_route: ["*"],
    required_for_commodity: ["*"],
    client_visible_default: false,
    icon: "Truck",
    color: "orange",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "cat-financial",
    name: "Financial Invoices & Payment Receipts",
    name_fa: "فاکتورها، رسیدات و حواله‌های پولی",
    code: "FINANCIAL",
    parent_category_id: null,
    description: "Customer Invoices, Freight Invoices, Supplier Bills, Bank Deposit Slips, Hawala Vouchers, and Payment Proofs.",
    active: true,
    required_for_route: ["*"],
    required_for_commodity: ["*"],
    client_visible_default: false, // Internal by default unless released
    icon: "Receipt",
    color: "teal",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "cat-photos",
    name: "Photos & Visual Inspection",
    name_fa: "عکس‌های بار، موتر و کانتینر",
    code: "PHOTOS",
    parent_category_id: null,
    description: "Time-stamped photos of cargo cartons, container seals, truck plates, stuffing/unloading, and damage reports.",
    active: true,
    required_for_route: ["*"],
    required_for_commodity: ["*"],
    client_visible_default: true,
    icon: "Camera",
    color: "purple",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "cat-other",
    name: "Other Supporting Files",
    name_fa: "سایر اسناد ضمیمه",
    code: "OTHER",
    parent_category_id: null,
    description: "General correspondence, email confirmations, border gate passes, and miscellaneous attachments.",
    active: true,
    required_for_route: ["*"],
    required_for_commodity: ["*"],
    client_visible_default: false,
    icon: "Folder",
    color: "slate",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const DEFAULT_REQUIREMENT_RULES: DocumentRequirementRule[] = [
  {
    id: "rule-commercial-invoice",
    name: "Commercial Invoice",
    document_type: "COMMERCIAL_INVOICE",
    document_category_code: "COMMERCIAL",
    is_mandatory: true,
    description: "Customs declaration invoice required for all commercial export and transit shipments.",
  },
  {
    id: "rule-packing-list",
    name: "Packing List",
    document_type: "PACKING_LIST",
    document_category_code: "COMMERCIAL",
    is_mandatory: true,
    description: "Itemized carton counts, net and gross weights required for container stuffing and customs inspections.",
  },
  {
    id: "rule-first-leg-bl",
    name: "First Leg / Master Bill of Lading",
    document_type: "FIRST_LEG_BL",
    document_category_code: "SHIPPING",
    is_mandatory: true,
    description: "Primary ocean or multimodal Bill of Lading for origin port carriage.",
  },
  {
    id: "rule-phyto",
    name: "Phytosanitary Certificate",
    document_type: "PHYTOSANITARY_CERTIFICATE",
    document_category_code: "CERTIFICATES",
    is_mandatory: true,
    commodity_pattern: "Dry Fruit,Raisins,Figs,Almonds,Pistachios,Agricultural,Seeds",
    description: "Agricultural plant health certificate required for dried fruit exports.",
  },
  {
    id: "rule-origin",
    name: "Certificate of Origin",
    document_type: "CERTIFICATE_OF_ORIGIN",
    document_category_code: "CERTIFICATES",
    is_mandatory: true,
    description: "Chamber of Commerce certificate proving the country of manufacture or harvest.",
  },
  {
    id: "rule-customs-afg",
    name: "Afghan Customs Clearance",
    document_type: "AFGHAN_CUSTOMS_CLEARANCE",
    document_category_code: "CUSTOMS",
    is_mandatory: true,
    route_pattern: "Afghanistan,Islam Qala,Torghundi,Hairatan,Spin Boldak,Kandahar,Kabul",
    description: "Border station export and transit release slip issued by Afghan customs authorities.",
  },
  {
    id: "rule-truck-reg",
    name: "Truck Registration & License",
    document_type: "TRUCK_REGISTRATION",
    document_category_code: "TRANSPORT",
    is_mandatory: false,
    description: "Afghan or Iranian truck vehicle registration documents.",
  },
  {
    id: "rule-driver-license",
    name: "Driver License & Tazkira",
    document_type: "DRIVER_LICENSE",
    document_category_code: "TRANSPORT",
    is_mandatory: false,
    description: "Driver identification and commercial driving credentials.",
  },
]
